### PR TITLE
Added Github action as CI

### PR DESCRIPTION
**Pull request by dlozano**
As alternative to travis.

### CODE REVIEW

**Comment by jellybob** [comment]
❤️ I was going to do this at some point in the near future, so thanks for getting ahead of me on it! I've been poking at this gem for two days straight now, so don't really have the energy to debug Github Actions should there be problems, but I'll look at getting this merged over the weekend.

**Comment by dlozano** [comment]
Thank you for taking over this gem maintenance.
There is no rush for this, I'll keep checking the issues in 2.2, 2.3 and 2.4 jobs meanwhile.

**Comment by dlozano** [comment]
I added a few fixes. Now is much more similar to the travis setup.

You can check the action execution log on my fork until you enable in your repo:  [GH action log](https://github.com/dlozano/mimemagic/pull/2/checks)

Details about the failed jobs:
* 2.1
  * Heredoc issue
  * minitest dependency
``` Bundler could not find compatible versions for gem "ruby":
    In Gemfile:
      ruby
  
      minitest (~> 5.14) was resolved to 5.14.1, which depends on
        ruby (~> 2.2)
```
* 2.2
  * Heredoc issue
```
rake aborted!
SyntaxError: ext/mimemagic/Rakefile:31: syntax error, unexpected <<, expecting ')'
    f.print(<<~SOURCE
              ^
ext/mimemagic/Rakefile:36: syntax error, unexpected ')', expecting keyword_end
/home/runner/work/mimemagic/mimemagic/Rakefile:5:in `load'
/home/runner/work/mimemagic/mimemagic/Rakefile:5:in `block in <top (required)>'
/home/runner/work/mimemagic/mimemagic/Rakefile:4:in `<top (required)>'
/home/runner/work/mimemagic/mimemagic/vendor/bundle/ruby/2.2.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.2.10/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.2.10/x64/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```
* jruby
  * redcarpet issue
```
  Fetching gem metadata from https://rubygems.org/......
  Fetching rake 13.0.3
  Installing rake 13.0.3
  Using bundler 2.2.15
  Using racc 1.5.2 (java)
  Fetching minitest 5.14.4
  Fetching redcarpet 3.5.1
  Fetching github-markup 3.0.5
  Fetching yard 0.9.26
  Installing minitest 5.14.4
  Installing github-markup 3.0.5
  Installing redcarpet 3.5.1 with native extensions
  Installing yard 0.9.26
  Fetching nokogiri 1.11.2 (java)
  Installing nokogiri 1.11.2 (java)
  Using mimemagic 0.4.3 from source at `.`
  Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
  
  current directory:
  /home/runner/work/mimemagic/mimemagic/vendor/bundle/jruby/2.5.0/gems/redcarpet-3.5.1/ext/redcarpet
  /home/runner/.rubies/jruby-9.2.16.0/bin/jruby -I
  /home/runner/.rubies/jruby-9.2.16.0/lib/ruby/stdlib -r
  ./siteconf20210329-1657-y6p08k.rb extconf.rb
  creating Makefile
  
  current directory:
  /home/runner/work/mimemagic/mimemagic/vendor/bundle/jruby/2.5.0/gems/redcarpet-3.5.1/ext/redcarpet
  make "DESTDIR=" clean
  
  current directory:
  /home/runner/work/mimemagic/mimemagic/vendor/bundle/jruby/2.5.0/gems/redcarpet-3.5.1/ext/redcarpet
  make "DESTDIR="
  make: *** No rule to make target
  '/home/runner/.rubies/jruby-9.2.16.0/lib/ruby/include/ruby/ruby.h', needed by
  'stack.o'.  Stop.
  
  make failed, exit code 2
  
  Gem files will remain installed in
  /home/runner/work/mimemagic/mimemagic/vendor/bundle/jruby/2.5.0/gems/redcarpet-3.5.1
  for inspection.
  Results logged to
  /home/runner/work/mimemagic/mimemagic/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/redcarpet-3.5.1/gem_make.out
  
  An error occurred while installing redcarpet (3.5.1), and Bundler cannot
  continue.
  Make sure that `gem install redcarpet -v '3.5.1' --source
  'https://rubygems.org/'` succeeds before bundling.
  
  In Gemfile:
    redcarpet
  Took  34.06 seconds
```

Maybe the most convenient is deprecating ruby versions lower than 2.3 in master/main and add workarounds to the 0.3 branch.
I could edit this branch and create one just for the 0.3 branch.

**Comment by dlozano** [comment]
I linked a PR with additional changes to also fix all jobs / ruby versions.

**Pull request closed without merging**
